#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         4
bspc config window_gap          20
bspc config focus_follows_pointer true
bspc config focused_border_color "#CE9681"
bspc config normal_border_color "#A29F87"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 desktop='^6'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a firefox desktop='^5'
bspc rule -a zen-alpha desktop='^5'
